import matplotlib.pyplot as plt
import numpy
from matplotlib import cm
from matplotlib.ticker import LinearLocator, FormatStrFormatter
from mpl_toolkits.mplot3d import Axes3D


def pic_1d(coef,set,sol):

    if set['k'] % 50 == 0:#set['t'] >= set['T']:  
        '''Chemotaxis velocity analysis'''        
        plt.figure(1)
        axes = plt.gca()
        plt.title('%s' % ('All'))
        plt.plot(sol['time'], sol['c'], 'g', linewidth=2.0, label = 'S')
        plt.plot(sol['time'], sol['A'], 'c', linewidth=2.0, label = 'A')
        plt.plot(sol['time'], sol['I'], 'm', linewidth=2.0, label = 'I')
        plt.plot(sol['time'], sol['Ki'], 'k', linewidth=2.0, label = 'R')
        plt.plot(sol['time'], sol['Q'], 'b', linewidth=2.0, label = 'Q')
        plt.legend(bbox_to_anchor=(0.85, 0.25), loc=0, borderaxespad=0.)
        plt.ylabel('value')
        plt.xlabel('t (time)')
        flag = 'all=%s' % str(sol['p_3']) 
        plt.savefig("%s.png" % flag)
        plt.close()
        
        plt.figure(2)
        axes = plt.gca()
        plt.title('%s' % ('S'))
        plt.plot(sol['time'], sol['c'], 'g', linewidth=2.0, label = 'S')
        plt.legend(bbox_to_anchor=(0.85, 0.25), loc=2, borderaxespad=0.)
        plt.ylabel('value')
        plt.xlabel('t (time)')
        flag = 'S=%s' % str(sol['p_3']) 
        plt.savefig("%s.png" % flag)
        plt.close()
        
        plt.figure(10)
        axes = plt.gca()
        plt.title('%s' % ('A'))
        plt.plot(sol['time'], sol['A'], 'c', linewidth=2.0, label = 'A')
        plt.legend(bbox_to_anchor=(0.85, 0.25), loc=0, borderaxespad=0.)
        plt.ylabel('value')
        plt.xlabel('t (time)')
        flag = 'A=%s' % str(sol['p_3']) 
        plt.savefig("%s.png" % flag)
        plt.close()
        
        plt.figure(11)
        axes = plt.gca()
        plt.title('%s' % ('I'))
        plt.plot(sol['time'], sol['I'], 'm', linewidth=2.0, label = 'I')
        plt.legend(bbox_to_anchor=(0.85, 0.25), loc=0, borderaxespad=0.)
        plt.ylabel('value')
        plt.xlabel('t (time)')
        flag = 'I=%s' % str(sol['p_3']) 
        plt.savefig("%s.png" % flag)
        plt.close()

        plt.figure(3)
        axes = plt.gca()
        plt.title('%s' % ('R'))
        plt.plot(sol['time'], sol['Ki'], 'k', linewidth=2.0, label = 'R')
        plt.legend(bbox_to_anchor=(0.85, 0.25), loc=2, borderaxespad=0.)
        plt.ylabel('value')
        plt.xlabel('t (time)')
        flag = 'R=%s' % str(sol['p_3']) 
        plt.savefig("%s.png" % flag)
        plt.close()
        
        plt.figure(4)
        axes = plt.gca()
        plt.title('%s' % ('A & I'))
        plt.plot(sol['time'], sol['A'], 'c', linewidth=2.0, label = 'A')
        plt.plot(sol['time'], sol['I'], 'm', linewidth=2.0, label = 'I')
        plt.legend(bbox_to_anchor=(0.85, 0.25), loc=0, borderaxespad=0.)
        plt.ylabel('value')
        plt.xlabel('t (time)')
        flag = 'AI=%s' % str(sol['p_3']) 
        plt.savefig("%s.png" % flag)
        plt.close()
        
        plt.figure(5)
        axes = plt.gca()
        plt.title('%s' % ('S & R'))
        plt.plot(sol['time'], sol['c'], 'g', linewidth=2.0, label = 'S')
        plt.plot(sol['time'], sol['Ki'], 'k', linewidth=2.0, label = 'R')
        plt.legend(bbox_to_anchor=(0.85, 0.25), loc=0, borderaxespad=0.)
        plt.ylabel('value')
        plt.xlabel('t (time)')
        flag = 'SR=%s' % str(sol['p_3']) 
        plt.savefig("%s.png" % flag)
        plt.close()
        
        plt.figure(6)
        axes = plt.gca()
        plt.title('%s' % ('Q'))
        plt.plot(sol['time'], sol['Q'], 'b', linewidth=2.0, label = 'Q')
        plt.legend(bbox_to_anchor=(0.85, 0.25), loc=2, borderaxespad=0.)
        plt.ylabel('value')
        plt.xlabel('t (time)')
        flag = 'Q=%s' % str(sol['p_3']) 
        plt.savefig("%s.png" % flag)
        plt.close()
        
        plt.figure(7)
        axes = plt.gca()
        plt.title('%s' % ('Q & R'))
        plt.plot(sol['time'], sol['Q'], 'b', linewidth=2.0, label = 'Q')
        plt.plot(sol['time'], sol['Ki'], 'k', linewidth=2.0, label = 'R')
        plt.legend(bbox_to_anchor=(0.85, 0.25), loc=0, borderaxespad=0.)
        plt.ylabel('value')
        plt.xlabel('t (time)')
        flag = 'QR=%s' % str(sol['p_3']) 
        plt.savefig("%s.png" % flag)
        plt.close()
        
        plt.figure(12)
        axes = plt.gca()
        plt.title('%s' % ('Q, S & R'))
        plt.plot(sol['time'], sol['Q'], 'b', linewidth=2.0, label = 'Q')
        plt.plot(sol['time'], sol['c'], 'g', linewidth=2.0, label = 'S')
        plt.plot(sol['time'], sol['Ki'], 'k', linewidth=2.0, label = 'R')
        plt.legend(bbox_to_anchor=(0.85, 0.25), loc=0, borderaxespad=0.)
        plt.ylabel('value')
        plt.xlabel('t (time)')
        flag = 'QSR=%s' % str(sol['p_3']) 
        plt.savefig("%s.png" % flag)
        plt.close()
        
        plt.figure(8)
        axes = plt.gca()
        plt.title('%s' % ('Q, A & I'))
        plt.plot(sol['time'], sol['Q'], 'b', linewidth=2.0, label = 'Q')
        plt.plot(sol['time'], sol['A'], 'c', linewidth=2.0, label = 'A')
        plt.plot(sol['time'], sol['I'], 'm', linewidth=2.0, label = 'I')
        plt.legend(bbox_to_anchor=(0.85, 0.25), loc=0, borderaxespad=0.)
        plt.ylabel('value')
        plt.xlabel('t (time)')
        flag = 'QAI=%s' % str(sol['p_3']) 
        plt.savefig("%s.png" % flag)
        plt.close()
        
        plt.figure(9)
        axes = plt.gca()
        plt.title('%s' % ('Q, A & I short'))
        plt.plot(sol['time'], sol['Q'], 'b', linewidth=2.0, label = 'Q')
        plt.plot(sol['time'], sol['A'], 'c', linewidth=2.0, label = 'A')
        plt.plot(sol['time'], sol['I'], 'm', linewidth=2.0, label = 'I')
        plt.legend(bbox_to_anchor=(0.85, 0.25), loc=0, borderaxespad=0.)
        plt.xlim(0,60)
        plt.ylim(0,1.2)
        plt.ylabel('value')
        plt.xlabel('t (time)')
        flag = 'QAIshort=%s' % str(sol['p_3']) 
        plt.savefig("%s.png" % flag)
        plt.close()



        
    return